@echo off
type "src\store\catalog.ts"
echo ===CATALOG===
type "src\store\compare.ts"
echo ===COMPARE===
type "src\store\cart.ts"
echo ===CART===
type "src\store\index.ts"
echo ===STORE_INDEX===
type "src\types\toast.ts"
echo ===TOAST_TYPES===
type "src\pages\ProductDetailPage.tsx"
echo ===PRODUCT_DETAIL===
type "src\pages\SupportPage.tsx"
echo ===SUPPORT_PAGE===
type "src\components\ScrollToTop.tsx"
echo ===SCROLL_TOP===
type "src\components\ToastProvider.tsx"
echo ===TOAST_PROVIDER===
type "src\components\Skeletons.tsx"
echo ===SKELETONS===
type "src\components\pages\ProductCard.tsx"
echo ===PRODUCT_CARD===
type "src\components\layout\Navbar.tsx"
echo ===NAVBAR===
type "src\Router.tsx"
echo ===ROUTER===
type "src\App.tsx"
echo ===APP===
type "src\pages\lazy.tsx"
echo ===LAZY===
type "tests\App.test.tsx"
echo ===APP_TEST===
type "tests\components\layout\Navbar.test.tsx"
echo ===NAVBAR_TEST===
type "tests\setup.ts"
echo ===SETUP===
type "tests\components\pages\Homepage.test.tsx"
echo ===HOMEPAGE_TEST===
type "tests\components\layout\AnnouncementBar.test.tsx"
echo ===ANN_TEST===
type "tests\components\layout\Footer.test.tsx"
echo ===FOOTER_TEST===
type "tests\components\ui\Button.test.tsx"
echo ===BUTTON_TEST===
type "tests\components\ui\Card.test.tsx"
echo ===CARD_TEST===
type "tests\components\ui\Input.test.tsx"
echo ===INPUT_TEST===
type "tests\components\ui\SectionHeading.test.tsx"
echo ===SECTION_TEST===
type "tests\components\ui\Select.test.tsx"
echo ===SELECT_TEST===
type "tests\components\ui\Tag.test.tsx"
echo ===TAG_TEST===
type "package.json"
echo ===PACKAGE===
type "vitest.config.ts"
echo ===VITEST_CONFIG===